name: 'SecHub reporter'
description: 'Make a report for SecHub results'

branding:
  icon: 'settings'
  color: 'blue'

inputs:
  file:
    required: true
    description: 'Path to SecHub JSON results file'
  modes:
    required: false
    description: |-
      A multi-line input with the following values:
      - pr-comment - report will be added as a comment on PR.
      - check - report will be added in a GitHub check.
      - summary - report will be added as a summary.
  token:
    required: true
    description: 'Your GitHub token'
    default: ${{ github.token }}
  fail-on-error:
    required: false
    description: 'Fail the action if errors are found on the report'
    default: 'false'
  consider-error-on-severities:
    required: false
    description: |-
      Consider the following severities as errors for this action.
      In addition to the severities supported by SecHub we have
      the following special values:
      - NONE - if you don't want to consider any severity as error
      - ALL - if you want to consider on all severities as errors
    default: ALL
  pr-filter-mode:
    required: false
    description: |-
      Filter mode for report findings in PR context. The following values are supported:
      - NONE - all findings will be reported
      - ENTRY_POINT - findings will be filtered based on matching entry point
      - CALL_HIERARCHY - findings will be filtered based on matching call hierarchy
    default: NONE
  comment-pr-on-success:
    required: false
    description: Comment on PR even if there are no findings
    default: 'true'
runs:
  using: node20
  main: dist/index.js
