name: 'SecHub reporter'
description: 'Make a report for SecHub results'

branding:
  icon: settings
  color: blue

inputs:
  file:
    required: true
    description: 'Path to SecHub JSON results file'
  modes:
    required: false
    description: |-
      A multi-line input with the following values:
      - pr-comment - report will be added as a comment on PR.
      - check - report will be added in a GitHub check.
      - summary - report will be added as a summary.
  token:
    required: true
    description: 'Your GitHub token'
    default: ${{ github.token }}
  fail-on-severities:
    required: false
    description: |-
      Fail the action if the given severities occur.
      In addition to the severities supported by SecHub we have
      the following special values:
      - NONE - if you don't want to fail the action when severities found
      - ALL - if you want to fail on all severities
    default: NONE
runs:
  using: 'node16'
  main: 'dist/index.js'
