name: Test

on: [push, pull_request]

permissions:
  contents: read
  packages: read
  checks: write
  pull-requests: write

jobs:
  test:
    strategy:
      matrix:
        modes: [pr-comment, check, summary]
        file: [sechub-result-error.json, sechub-result-ok.json]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: SecHub reporter test
        uses: ./
        with:
          file: ./__tests__/${{ matrix.file }}
          modes: ${{ matrix.modes }}
  test-multi-mode:
    strategy:
      matrix:
        file: [ sechub-result-error.json, sechub-result-ok.json ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: SecHub reporter test
        uses: ./
        with:
          file: ./__tests__/${{ matrix.file }}
          modes: |
            pr-comment
            check
  test-fail-on-error:
    strategy:
      matrix:
        file: [ sechub-result-error.json, sechub-result-ok.json ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: SecHub reporter test
        uses: ./
        with:
          file: ./__tests__/${{ matrix.file }}
          modes: summary
          fail-on-error: true
        continue-on-error: true
