name: Test

on: [push, pull_request]

permissions:
  contents: read
  packages: read
  checks: write
  pull-requests: write

jobs:
  test:
    strategy:
      matrix:
        modes: [pr-comment, check, summary]
        file: [sechub-result-error.json, sechub-result-ok.json]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: SecHub reporter test
        uses: ./
        with:
          file: ./__tests__/${{ matrix.file }}
          modes: ${{ matrix.modes }}
  test-multi-mode:
    strategy:
      matrix:
        file: [ sechub-result-error.json, sechub-result-ok.json ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: SecHub reporter test
        uses: ./
        with:
          file: ./__tests__/${{ matrix.file }}
          modes: |
            pr-comment
            check
  test-error-scenarios:
    strategy:
      matrix:
        file: [ sechub-result-error.json, sechub-result-ok.json ]
        consider-error-on-severities: [ALL, NONE, HIGH, MEDIUM, LOW]
        fail-on-error: [true, false]
        pr-filter-mode: [NONE, ENTRY_POINT, CALL_HIERARCHY]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: SecHub reporter test
        uses: ./
        with:
          file: ./__tests__/${{ matrix.file }}
          modes: summary
          fail-on-error: ${{ matrix.fail-on-error }}
          consider-error-on-severities: ${{ matrix.consider-error-on-severities }}
          pr-filter-mode: ${{ matrix.pr-filter-mode }}
        continue-on-error: true
